config/routes.rb
Logistic::Application.routes.draw do
 
  resources :report_activity_users

  match '/login', :to => 'user_sessions#new'
  match '/logout',:to => 'user_sessions#destroy'
  resources :user_sessions

  
  resources :vmodules do 
    resources :users    
  end

  resources :main_activities do 
    resources :activities
  end   
  
  
  resources :averages
  resources :machines
  resources :assigned_main_activities

  resources :vmodules do
    member do
      get 'update_span'
      get 'update_worker'
    end
  end

  root :to => "vmodules#index"

end

app/models/main_activity.rb
class MainActivity < ActiveRecord::Base
  belongs_to :assigned_main_activity
  has_many :activities
  attr_accessible :description, :time_main_activity, :name
end

app/controllers/main_activities_controller.rb
class MainActivitiesController < ApplicationController
  before_filter :current_user?
  before_filter :is_admin?, :only => :index
  def index
    @main_activities = MainActivity.all
  end

  def show
    @main_activity = MainActivity.find(params[:id])
  end

  def new
    @main_activity = MainActivity.new
  end

  def create
    @main_activity = MainActivity.new(params[:main_activity])
    if @main_activity.save
      redirect_to @main_activity, :notice => "Successfully created main activity."
    else
      render :action => 'new'
    end
  end

  def edit
    @main_activity = MainActivity.find(params[:id])
  end

  def update
    @main_activity = MainActivity.find(params[:id])
    if @main_activity.update_attributes(params[:main_activity])
      redirect_to @main_activity, :notice  => "Successfully updated main activity."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @main_activity = MainActivity.find(params[:id])
    @main_activity.destroy
    redirect_to main_activities_url, :notice => "Successfully destroyed main activity."
  end
end

app/helpers/main_activities_helper.rb
module MainActivitiesHelper
end

app/views/main_activities/_form.html.erb
<%= form_for @main_activity do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :time_main_activity %><br />
    <%= f.text_field :time_main_activity %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/main_activities/edit.html.erb
<% title "Edit Main Activity" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @main_activity %> |
  <%= link_to "View All", main_activities_path %>
</p>

app/views/main_activities/index.html.erb
<% title "Main Activities" %>

<table class= "table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Time Main Activity</th>
  </tr>
  <% for main_activity in @main_activities %>
    <tr>
      <th><%= main_activity.name %></th>
      <td><%= main_activity.description %></td>
      <td><%= main_activity.time_main_activity %></td>
      <td><%= link_to "Show", main_activity %></td>
      <td><%= link_to "Edit", edit_main_activity_path(main_activity) %></td>
      <td><%= link_to "Destroy", main_activity, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Main Activity", new_main_activity_path %></p>

app/views/main_activities/new.html.erb
<% title "New Main Activity" %>

<%= render 'form' %>

<p><%= link_to "Back to List", main_activities_path %></p>

app/views/main_activities/show.html.erb
<% title "Main Activity" %>

<p>
  <strong>Name:</strong>
  <%= @main_activity.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @main_activity.description %>
</p>
<p>
  <strong>Time Main Activity:</strong>
  <%= @main_activity.time_main_activity %>
</p>

  <strong>Activities:</strong>
  <% for activity in @main_activity.activities do %>
    <p><%= activity.name %></p>
    <p><%= activity.description%></p>
  <% end %>


<% admin_area do %>
  <%= link_to "Edit", edit_main_activity_path(@main_activity) %> |
  <%= link_to "Destroy", @main_activity, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Add activities", new_main_activity_activity_path(@main_activity) %> |
  <%= link_to "View All", main_activities_path %>
<% end %>