config/routes.rb
Logistic::Application.routes.draw do
 
  resources :report_activity_users

  match '/login', :to => 'user_sessions#new'
  match '/logout',:to => 'user_sessions#destroy'
  resources :user_sessions

  
  resources :vmodules do 
    resources :users    
  end

  resources :main_activities do 
    resources :activities
  end   
  
  
  resources :averages
  resources :machines
  resources :assigned_main_activities

  resources :vmodules do
    member do
      get 'update_span'
      get 'update_worker'
    end
  end

  root :to => "vmodules#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |c|
    c.logged_in_timeout = 10.minutes
  end
  
  belongs_to :vmodule
  has_many :averages
  belongs_to :activity

  attr_accessible :username, :email, :password, :password_confirmation, :vmodule_id, :user_efficiency, :age, :admin
  
  def compliance
    reports = ReportActivityUser.find(:all,:conditions => {:user_id => self.id})
    unless reports.nil?
      den =0
      num =1
      for report in reports do 
        den += report.activity.time_activity
        num += report.real_time
      end
      div = den / num
      return sprintf("%.2f", div)
    else
      return "NA"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :current_user?

  def index
    @vmodule = Vmodule.find(params[:vmodule_id])
    @users = User.all
  end

  def show
    @vmodule = Vmodule.find(params[:vmodule_id])
    @user = @vmodule.users.find(params[:id])
  end

  def new
    @vmodule = Vmodule.find(params[:vmodule_id])
    @user = @vmodule.users.new
  end

  def create
    @vmodule = Vmodule.find(params[:vmodule_id])
    @user = @vmodule.users.new(params[:user])
    if @user.save
      redirect_to @vmodule, :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @vmodule = Vmodule.find(params[:vmodule_id])
    @user = @vmodule.users.find(params[:id])
  end

  def update
    @vmodule = Vmodule.find(params[:vmodule_id])
    @user = @vmodule.users.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @vmodule, :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to vmodules_path, :notice => "Successfully destroyed user."
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_information user
      content_tag(:div, :class => "user_information") do
          content_tag(:div, image_tag('avatar.jpg')) <<
          content_tag(:p, "Name: #{user.username}") <<
          content_tag(:p, "Age: #{user.age}") <<
          content_tag(:p, "Current compliance: #{user.compliance}") <<      
          content_tag(:p, "email: #{user.email}") 
      end
  end

end

app/views/users/_form.html.erb
<%= form_for [@user.vmodule, @user] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label t(:username) %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label t(:email) %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label t(:age) %><br />
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.label t(:password) %><br />
    <%= f.password_field :password %>
  </p>
   <p>
    <%= f.label t(:password_confirmation) %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Edit User" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", vmodule_user_path(@user.vmodule, @user) %> |
  <%= link_to "View All", vmodule_path(@user.vmodule) %>
</p>

app/views/users/index.html.erb
<% title "Users" %>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Password</th>
    <th>Module</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.password %></td>
      <td><%= user.vmodule_id %></td>
      <td><%= link_to "Show", user %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Destroy", user, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New User", new_user_path %></p>

app/views/users/new.html.erb
<% title "New User" %>

<%= render 'form' %>

<p><%= link_to "Back to List", @vmodule %></p>

app/views/users/show.html.erb
<% title "User #{@user.username}" %>


<%= user_information @user %>

<% admin_area do %>
  <% if admin? or @user == current_user %>
    <%= link_to t(:edit), edit_vmodule_user_path(@user.vmodule,@user) %> |
    <%= link_to t(:destroy), [@user.vmodule,@user], :confirm => 'Are you sure?', :method => :delete %> |
    <%= link_to t(:return_to_module), vmodule_path(@user.vmodule) %>
  <% else %>
    <%= link_to t(:return_to_module), vmodule_path(@user.vmodule) %>
  <% end %>
<% end %>