config/routes.rb
Logistic::Application.routes.draw do
 
  resources :report_activity_users

  match '/login', :to => 'user_sessions#new'
  match '/logout',:to => 'user_sessions#destroy'
  resources :user_sessions

  
  resources :vmodules do 
    resources :users    
  end

  resources :main_activities do 
    resources :activities
  end   
  
  
  resources :averages
  resources :machines
  resources :assigned_main_activities

  resources :vmodules do
    member do
      get 'update_span'
      get 'update_worker'
    end
  end

  root :to => "vmodules#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :main_activity
  belongs_to :machine
  has_many :averages
  has_many :report_activity_users
  attr_accessible :description, :time_activity, :name
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_filter :current_user?
  before_filter :is_admin?, :only => :index
  def index
    @main_activity = MainActivity.find(params[:main_activity_id])
    @activities = Activity.all
  end

  def show
    @main_activity = MainActivity.find(params[:main_activity_id])
    @activity = Activity.find(params[:id])
  end

  def new
    @main_activity = MainActivity.find(params[:main_activity_id])
    @activity = @main_activity.activities.build
  end

  def create
    @main_activity = MainActivity.find(params[:main_activity_id])
    @activity = @main_activity.activities.new(params[:activity])
    if @activity.save
      redirect_to @main_activity, :notice => "Successfully created activity."
    else
      render :action => 'new'
    end
  end

  def edit
    @main_activity = MainActivity.find(params[:main_activity_id])
    @activity = @main_activity.activities.find(params[:id])
  end

  def update
    @main_activity = MainActivity.find(params[:main_activity_id])
    @activity = @main_activity.activities.find(params[:id])
    if @activity.update_attributes(params[:activity])
      redirect_to @activity, :notice  => "Successfully updated activity."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to activities_url, :notice => "Successfully destroyed activity."
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for [@main_activity , @activity] do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :time_activity %><br />
    <%= f.text_field :time_activity %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/activities/edit.html.erb
<% title "Edit Activity" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @activity %> |
  <%= link_to "View All", activities_path %>
</p>

app/views/activities/index.html.erb
<% title "Activities" %>

<table>
  <tr>
    <th>Description</th>
    <th>Time Activity</th>
  </tr>
  <% for activity in @activities %>
    <tr>
      <td><%= activity.description %></td>
      <td><%= activity.time_activity %></td>
      <td><%= link_to "Show", activity %></td>
      <td><%= link_to "Edit", edit_main_activity_activity_path(@main_activity) %></td>
      <td><%= link_to "Destroy", [@main_activity,activity], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Activity", new_main_activity_activity_path(@main_activity) %></p>

app/views/activities/new.html.erb
<% title "New Activity" %>

<%= render 'form' %>

<p><%= link_to "Back to List", main_activities_path %></p>

app/views/activities/show.html.erb
<% title "Activity" %>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>
<p>
  <strong>Time Activity:</strong>
  <%= @activity.time_activity %>
</p>

<p>
  <%= link_to "Edit", edit_activity_path(@activity) %> |
  <%= link_to "Destroy", @activity, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", activities_path %>
</p>