config/routes.rb
Logistic::Application.routes.draw do
 
  resources :report_activity_users

  match '/login', :to => 'user_sessions#new'
  match '/logout',:to => 'user_sessions#destroy'
  resources :user_sessions

  
  resources :vmodules do 
    resources :users    
  end

  resources :main_activities do 
    resources :activities
  end   
  
  
  resources :averages
  resources :machines
  resources :assigned_main_activities

  resources :vmodules do
    member do
      get 'update_span'
      get 'update_worker'
    end
  end

  root :to => "vmodules#index"

end

app/models/vmodule.rb
class Vmodule < ActiveRecord::Base
  has_many :users
  has_many :main_activity
  attr_accessible :vmodule_number, :vmodule_efficiency, :user_id
  
  def compliance
    total_users = self.users.count
    if total_users != 0
      total_compliance = 0
      for user in self.users do
        total_compliance += user.compliance.to_f
      end
      compliance = total_compliance/total_users
      return compliance
    else
      return 0
    end
  end
end

app/controllers/vmodules_controller.rb
class VmodulesController < ApplicationController
  before_filter :current_user?
  before_filter :is_admin?, :only => :index
  def index
    @vmodules = Vmodule.all
  end

  def show
    @vmodule = Vmodule.find(params[:id])
  end

  def new
    @vmodule = Vmodule.new
  end

  def create
    @vmodule = Vmodule.new(params[:vmodule])
    if @vmodule.save
      redirect_to @vmodule, :notice => "Successfully created vmodule."
    else
      render :action => 'new'
    end
  end

  def edit
    @vmodule = Vmodule.find(params[:id])
  end

  def update
    @vmodule = Vmodule.find(params[:id])
    if @vmodule.update_attributes(params[:vmodule])
      redirect_to @vmodule, :notice  => "Successfully updated vmodule."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @vmodule = Vmodule.find(params[:id])
    @vmodule.destroy
    redirect_to vmodules_url, :notice => "Successfully destroyed vmodule."
  end

  def update_span
    @vmodules = Vmodule.all
    render :layout => false
  end

  def update_worker
    @vmodule = Vmodule.find(params[:id])
    render :layout =>false
  end
end

app/helpers/vmodules_helper.rb
module VmodulesHelper

  def main_information vmodule
    content_tag(:div, :class => 'main_information') do
      content_tag(:strong, (t(:vmodule_efficiency))) <<
      content_tag(:strong, (vmodule.vmodule_efficiency))
    end
  end

  def small_user_information user
    if user.compliance.to_f < 0.9
      content_tag(:td,:class => 'small_information', :id => "small_user-red") do
        content_tag(:span,(link_to "#{user.username}(#{user.compliance})", vmodule_user_path(user.vmodule,user))) <<
          content_tag(:div,(link_to image_tag('rojo.jpg'), vmodule_user_path(user.vmodule,user))) 
      end 
    else
      content_tag(:td,:class => 'small_information', :id => "small_user-green") do
        content_tag(:span, (link_to "#{user.username}(#{user.compliance})", vmodule_user_path(user.vmodule,user))) <<
          content_tag(:div,(link_to image_tag('verde.jpg'), vmodule_user_path(user.vmodule,user))) 
      end
    end
  end

  def small_module_information vmodule
    if vmodule.compliance < 0.9
       content_tag(:td,:class => 'small_information', :id => "small-red") do
        content_tag(:span,(link_to vmodule.vmodule_number, vmodule_path(vmodule),:id => "numberdb")) <<
        content_tag(:div,(link_to image_tag('rojo.jpg'), vmodule_path(vmodule))) 
      end 
    else
      content_tag(:td,:class => 'small_information', :id => "small-green") do
        content_tag(:span, (link_to vmodule.vmodule_number, vmodule_path(vmodule), :id => "numberdb")) <<
        content_tag(:div,(link_to image_tag('verde.jpg'), vmodule_path(vmodule))) 
      end
    end
  end
end

app/views/vmodules/_form.html.erb
<%= form_for @vmodule do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label t(:vmodule_number) %><br />
    <%= f.text_field :vmodule_number %>
  </p>
  <p>
    <%= f.label t(:compliance) %><br />
    <%= f.text_field :vmodule_efficiency %>
  </p>
  <p><%= f.submit t(:submit) %></p>
<% end %>

app/views/vmodules/_small_information.html.erb
<%= small_module_information vmodule %>

app/views/vmodules/edit.html.erb
<% title "Edit Vmodule" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @vmodule %> |
  <%= link_to "View All", vmodules_path %>
</p>

app/views/vmodules/index.html.erb
<% title t :vmodules %>

<div class= "content-area">
  <table id=  "all-modules">
    <% for vmodule in @vmodules %>
      <%= render :partial =>"small_information", :locals => {:vmodule => vmodule} %>
    <% end %>
  </table>
</div>
<p><%= link_to t(:new_vmodule), new_vmodule_path %></p>

app/views/vmodules/new.html.erb
<% title t(:new_vmodule) %>

<%= render 'form' %>

<p><%= link_to "Back to List", vmodules_path %></p>

app/views/vmodules/show.html.erb
<% title [t(:vmodule),@vmodule.vmodule_number.to_s].join("  ") %>
<%= main_information @vmodule %>
<div id= "content-area">
  <table id="table-users">
    <% for user in @vmodule.users do %>
      <%= small_user_information user %>
    <% end %>
  </table>
</div>

<% if admin? %>
  <% admin_area do %>
    <%= link_to t(:edit), edit_vmodule_path(@vmodule) %> |
    <%= link_to t(:destroy), @vmodule, :confirm => 'Are you sure?', :method => :delete %> |
    <%= link_to t(:add_user), new_vmodule_user_path(@vmodule) %> |
    <%= link_to t(:view_all_modules), vmodules_path %>
  <% end %>
<% end %>

<script type= "text/javascript">

  function objetoAjax(){
     var xmlhttp=false;
     try {
		xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
	} catch (e) {
		try {
		   xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
		} catch (E) {
		    xmlhttp = false;
  		}
	}
	if (!xmlhttp && typeof XMLHttpRequest!='undefined') {
		xmlhttp = new XMLHttpRequest();
	}
	return xmlhttp;
  }

  function actualizarUsers(){

	divResultado = document.getElementById('table-users');
	ajax=objetoAjax();
        if (divResultado != null){
            ajax.open("GET", "<%="/vmodules/#{@vmodule.id}/update_worker" %>");
	    ajax.onreadystatechange=function() {
		if (ajax.readyState==4) {
		    //mostrar resultados en esta capa
		    divResultado.innerHTML = ajax.responseText
		    //llamar a funcion para limpiar los inputs
		}
		
	    }
	    //enviando los valores
	    ajax.send(null);
            setTimeout("actualizarUsers()",1000);
	}
    
  }
setTimeout("actualizarUsers()",1000);

</script>

app/views/vmodules/update_span.html.erb
 <% for vmodule in @vmodules %>
      <%= render :partial =>"small_information", :locals => {:vmodule => vmodule} %>
 <% end %>

app/views/vmodules/update_worker.html.erb
 <% for user in @vmodule.users do %>
      <%= small_user_information user %>
 <% end %>